### ISSUE TITLE
Create a non-UUID FkField for DAL

### ISSUE THREAD

**Issue by windaishi** [VIISON/shopware-platform#9]
We are currently using the following work-around to allow non-UUID FkField for models:

https://github.com/VIISON/shopware-platform/commit/e5e92b629c5b3e3cd42d7f3fc28c4e9db17596bb#diff-9eba54da668696130c83af083e31aa41

Instead of changing shopware's code we need a new PR to shopware/platform that adds a new Field and a corresponding FieldSerializer named NonUuidFkField that do the same.

**Comment by fixpunkt** [comment]
We've created non-UUID FK fields which we can ship with our plugins.
